### ISSUE TITLE
UserChannelPermission MANAGE_MESSAGES is not checked

### ISSUE THREAD

**Issue by Grafikart** [discordeno/discordeno-bot-template#70]
When running this template any user on my server can call the `!purge` command. It seems that the system doesn't detect the permission MANAGE_MESSAGES correctly.

## Additional informations

I updated the moderator role so it's based on the same permission

```js
    memberIDHasPermission(
      message.author.id,
      message.guildID,
      ["MANAGE_MESSAGES"],
    ),
```

then used this role for the purgeCommand

```js
  permissionLevels: [PermissionLevels.MODERATOR],
```

and the permission work correctly in this case. The problem may come from the check on the message

**Comment by itohatweb** [comment]
This was an Issue with the lib itself. Which is already fixed. Please close this issue.
