### ISSUE TITLE
Still slow as hell

### ISSUE THREAD

**Issue by lepidotteri** [discordeno/discordeno-bot-template#79]
solve it

**Comment by ayntee** [comment]
Hey there! Could you provide more details as to what you are referring to?

**Comment by itohatweb** [comment]
The Boilerplate is not so slow. Also it is only an example of how you can approach things using discordeno. It is not a bot template you can just throw in and use for a big bot.
(Ayntee already wrote it: You cannot expect help if you don't provide any information at all.)

**Comment by lepidotteri** [comment]
> Hey there! Could you provide more details as to what you are referring to?

Of course! It's incredibly slow, beyond the pale, when first populating its cache by having Deno scan and read all files in the relevant folders (commands, events, etc.).

With a i9-9900k at 5GHz and 64GB 4000Mhz RAM it takes around 1 minute to load the boilerplate up (or restart it for the matter!). Completely unacceptable.

Re-engineer the boilerplate to make cache loading optional at the very least.

Deno bots will never replace Golang bots

![image](https://user-images.githubusercontent.com/45174270/105346218-9461ae00-5be5-11eb-8049-5253141c346c.png)

**Comment by itohatweb** [comment]
So starting takes so long because we are forcing Deno to import all files in the `src` folder. BUT this only takes so long once at initial start-up after only files that were changes get recompiled.

**Comment by itohatweb** [comment]
If you have issues with the files getting compiled every time this is not an issue with this boilerplate but with Deno itself.

**Comment by lepidotteri** [comment]
> So starting takes so long because we are forcing Deno to import all files in the `src` folder. BUT this only takes so long once at initial start-up after only files that were changes get recompiled.

Is Deno a joke?

> If you have issues with the files getting compiled every time this is not an issue with this boilerplate but with Deno itself.

Deno is very much a joke atm

**Comment by itohatweb** [comment]
What do you mean with `joke`?

**Comment by ayntee** [comment]
> > So starting takes so long because we are forcing Deno to import all files in the `src` folder. BUT this only takes so long once at initial start-up after only files that were changes get recompiled.
> 
> Is Deno a joke?
> 
> > If you have issues with the files getting compiled every time this is not an issue with this boilerplate but with Deno itself.
> 
> Deno is very much a joke atm

Deno type-checks each module that is loaded, you can specify the `--no-check` flag to the `deno run` command to disable type-check.
