### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Kayxue** [discordeno/discordeno-bot-template#81]
![image](https://user-images.githubusercontent.com/26020165/105657246-e9ac0100-5efe-11eb-8e27-3e71d5510280.png)

**Comment by itohatweb** [comment]
Could you please provide more specific details about the error you are getting?

**Comment by Kayxue** [comment]
![image](https://user-images.githubusercontent.com/26020165/105835156-68d82c80-6006-11eb-8751-59d6d3eb8d4b.png)

**Comment by itohatweb** [comment]
That is not an error with this boilerplate. You need to install the Deno extension for vscode. And then Press F1+`deno: Init`

**Comment by ayntee** [comment]
> ![image](https://user-images.githubusercontent.com/26020165/105835156-68d82c80-6006-11eb-8751-59d6d3eb8d4b.png)

Hey there! Looks like you do not have the Deno extension for Visual Studio Code. Follow the instructions here to install the extension: https://deno.land/manual@v1.7.0/getting_started/setup_your_environment#vs-code

Still have questions in your mind? Feel free to join [our Discord server](https://discord.gg/5vBgXk3UcZ).
